apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <your eamil>
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudDNS:
            project: <project id>
            serviceAccountSecretRef:
              name: <service account secret name>
              key: <service account json key>
        selector:
          dnsZones:
            - example.com